version: 1
# This setting disables existing loggers to avoid duplicate log messages.
disable_existing_loggers: False

# Define the formatters for log messages. Formatters specify the layout of log messages.
formatters:
  simple:
    # The 'format' specifies the format of the log messages. The following placeholders are used:
    # %(asctime)s - The date and time of the log message.
    # %(name)s - The name of the logger that generated the message.
    # %(levelname)s - The log level (e.g., DEBUG, INFO, WARNING, ERROR, CRITICAL).
    # %(message)s - The log message.
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

# Define the handlers that determine where the log messages will go.
handlers:
  console:
    # StreamHandler outputs log messages to a stream (e.g., stdout).
    class: logging.StreamHandler
    # The minimum log level for this handler. Only messages with this level or higher will be handled.
    level: DEBUG
    # The formatter to use for this handler.
    formatter: simple
    # The stream where the log messages will be sent. 'ext://sys.stdout' refers to the standard output.
    stream: ext://sys.stdout

  file_handler:
    # FileHandler outputs log messages to a file.
    class: logging.FileHandler
    # The minimum log level for this handler. Only messages with this level or higher will be handled.
    level: DEBUG
    # The formatter to use for this handler.
    formatter: simple
    # The name of the file where log messages will be written.
    filename: logs/app.log

# Define loggers that will use the handlers. Loggers are used to log messages in different parts of the application.
loggers:
  my_module:
    # The minimum log level for this logger. Only messages with this level or higher will be logged.
    level: DEBUG
    # The handlers that this logger will use to output log messages.
    handlers: [console, file_handler]
    # Prevent log messages from being propagated to the root logger, which avoids duplicate logging.
    propagate: no

# The root logger configuration. The root logger is the default logger used by the application.
root:
  # The minimum log level for the root logger. Only messages with this level or higher will be logged.
  level: INFO
  # The handlers that the root logger will use to output log messages.
  handlers: [console, file_handler]
